---

version: 2.1

jobs:

  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#machine
      image: ubuntu-2004:202201-02
    environment:
      ANSIBLE_PYTHON_INTERPRETER: /usr/bin/python3

    steps:
      - run: sudo rm /etc/apt/sources.list.d/google.list /etc/apt/sources.list.d/heroku.list
      - run: sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-backports main universe restricted multiverse"
      - run: sudo apt-get update
      - run: sudo apt remove --assume-yes --purge apparmor
      - run: sudo apt install --assume-yes net-tools
      - run: pip3 install ansible ansible-lint

      - run: ansible --version
      - run: ansible-lint --version

      - checkout

      - run: printf '[defaults]\nroles_path=../' > ansible.cfg
      - run: ansible-lint

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run:
          command: sudo journalctl --no-pager --unit=redis-server
          when: on_fail
      - run:
          command: sudo cat /etc/redis/users.acl
          when: on_fail
      - run:
          command: sudo cat /var/log/redis/redis-server.log
          when: on_fail

      - run: ansible-playbook tests/test.yml -i tests/inventory --connection=local

      - run: redis-cli --version
      - run: redis-cli INFO
      - run: netstat -lnp
